In [1]:
import pandas as pd
import numpy as np
import os

from servicerequestslib.preprocessing import preprocessingSR
from servicerequestslib.vector_inference import obtain_embeddings
from servicerequestslib.vector_similarity import list_similar_embeddings, get_list_of_similar_SR

In [2]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

True

In [3]:
df = pd.read_csv('tests/fixtures/miniSRdf.csv')
df.head(3)

,u_case_number,u_case_requestor,u_opened_by,u_opened,u_original_type_of_issue,u_current_type_of_issue,u_issue_event_date,u_project_phase,u_customer_responsibility_addi,u_suggested_by_red_flag_review,...,u_product_safety,u_system_impacted,u_module_yard_case,u_outage_delay_1_day,u_system_unknown,u_watch_list,u_site_forecast_cost,u_actualize_cost,u_duplicated_sr,u_sr
0,90259175,"Lokombo, Johnny (105058889)","Lokombo, Johnny (105058889)",2016-06-05 16:16:02,Technical,Technical,2016-06-05,In Operation/Stand By,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,90234207,"Panzera, Michele (105034503)","Panzera, Michele (105034503)",2015-07-04 02:05:58,Technical,Technical,2015-06-30,Installation,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,90373306,"Shabad, Srikanth Reddy (212365091)","Shabad, Srikanth Reddy (212365091)",2020-01-30 04:42:29,Material,Material,2020-01-27,New Unit/Upgrades Installation,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
columns_dict = {"C_CASE_NUMBER": 'u_case_number',
                "C_DESCRIPTION": 'u_problem_description',
                "C_SOLUTION": 'u_solution_description',
                "C_EAD": 'u_expert_assessment_descriptio', 
                "C_FR": 'u_first_reply_solution'}
transformed_df = preprocessingSR(df, **columns_dict)

In [5]:
# transformed_df.to_csv('tests/fixtures/transformed_df.csv', index=False)

In [6]:
embeddings = obtain_embeddings(transformed_df)

In [7]:
embeddings.head(3)

,0,1,2,3,4,5,6,7,8,9,...,758,759,760,761,762,763,764,765,766,767
u_case_number,,,,,,,,,,,,,,,,,,,,,
90259175,0.154614,-0.117206,-0.194646,0.472344,-0.046092,0.008356,0.199978,-0.615417,-0.239320,0.090605,...,0.302076,0.448214,0.584998,0.378256,0.285880,-0.402414,-0.714580,-0.437146,0.163592,-0.021282
90234207,-0.215241,-0.551809,0.064129,0.835790,-0.488884,0.083674,0.111029,-0.643042,-0.145436,0.032675,...,0.643159,0.093414,0.301673,-0.248021,-0.165630,0.237210,0.037353,-0.184007,0.498661,-0.092548
90373306,-0.071186,-0.211480,0.080706,-0.567153,-1.035714,0.504875,-0.287359,-0.524392,0.104979,-0.166035,...,0.362862,0.092720,-0.104875,0.392049,-0.479631,-0.162846,-0.045231,0.881543,0.351948,-0.331644

In [8]:
# embeddings.to_csv('tests/fixtures/embeddings_df.csv')

In [9]:
embeddings.index[2]

90373306

In [10]:
similar = list_similar_embeddings(embeddings.index[2], embeddings, quantity_threshold=10, query_identifier='testing_mini_df')

In [11]:
similar

u_case_number
90205950    0.686987
90392794    0.676746
90201907    0.644419
90371348    0.636702
90245598    0.635645
90265629    0.619230
90249624    0.616735
90330100    0.610806
90364720    0.598836
90204194    0.598614
Name: testing_mini_df, dtype: float64

In [12]:
# embeddings = df.append({'A': i}, ignore_index=True)

In [13]:
new_sr_description = 'this is a test description'
new_sr_dict = {'u_case_number': 12345,
               'u_problem_description': new_sr_description,
               'u_solution_description': '',
               'u_expert_assessment_descriptio': '', 
               'u_first_reply_solution': ''}

new_sr_df = pd.DataFrame(new_sr_dict, index=[1])

In [14]:
updated_df = df.append(new_sr_dict, ignore_index=True) #Add sr_dict to sr_df
updated_df.tail()

,u_case_number,u_case_requestor,u_opened_by,u_opened,u_original_type_of_issue,u_current_type_of_issue,u_issue_event_date,u_project_phase,u_customer_responsibility_addi,u_suggested_by_red_flag_review,...,u_module_yard_case,u_outage_delay_1_day,u_system_unknown,u_watch_list,u_site_forecast_cost,u_actualize_cost,u_duplicated_sr,u_sr,CLEAN_expert_assessment_desc,_TEXT_LONG
496,90323687,"Gigliano, Errico (105033168)","Gigliano, Errico (105033168)",2018-04-14 04:11:18,Technical,Technical,2018-04-13,New Unit/Upgrades Commissioning/Start Up,0.0,0.0,...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Drain pipe line was open for both unit to drai...,Water contamination inside compressor M03 A - ...
497,90393530,"Christ dhas, Lenin christopher (105047330)","Christ dhas, Lenin christopher (105047330)",2020-11-26 06:02:24,Technical,Technical,2020-11-26,In Operation/Stand-by/Start up after out,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,close the case.,"In Compressor diaphragms found damage , can yo..."
498,90344557,"Mazzei, Samuele (105058122)","Mazzei, Samuele (105058122)",2019-01-10 19:18:13,Material,Material,2019-01-09,New Unit/Upgrades Installation,0.0,0.0,...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,The items requested will be at site with the n...,"At site and in the cargo list, we could not fi..."
499,90366821,"Dekkiche, Abderrazak (503068948)","Dekkiche, Abderrazak (503068948)",2019-10-22 09:27:34,Material,Material,2019-10-22,New Unit/Upgrades Commissioning/Start Up,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Smoke detector found faulty at Site\r\nPO warr...,we need one transducer for smoke detector omd-...
500,12345,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
one_transformed_df = preprocessingSR(updated_df.iloc[-1:], **columns_dict) #Preprocess sr_dict row

/usr/local/lib/python3.8/dist-packages/pandas/core/frame.py:4524: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().replace(
/workspace/giacomo/servicerequests_ak/servicerequestslib/preprocessing.py:111: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['CLEAN_expert_assessment_desc'] = df.apply(lambda row: switch_fr_assessment(row[C_EAD], row[C_FR]), axis=1)
/workspace/giacomo/servicerequests_ak/servicerequestslib/preprocessing.py:113: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[C_TEXT_LONG] = df[C_DESCRIPTION] + '. ' + df[C_SOLUTION].fillna('') + '. ' + df[
/workspace/giacomo/servicerequests_ak/servicerequestslib/preprocessing.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[C_TEXT_LONG] = df[C_TEXT_LONG].apply(clean_sentences_SR)

In [16]:
one_embedding = obtain_embeddings(one_transformed_df) #extract embeddings for sr_dict row

In [17]:
one_embedding

,0,1,2,3,4,5,6,7,8,9,...,758,759,760,761,762,763,764,765,766,767
u_case_number,,,,,,,,,,,,,,,,,,,,,
12345,-0.014201,-0.245703,0.3422,0.155851,0.469777,-0.2308,-0.065234,0.391865,-0.030472,-0.013436,...,0.215368,-0.091663,0.236904,-0.42465,-0.076784,-0.107422,0.667569,-0.480958,-0.041286,0.019768

In [18]:
embeddings.shape

(500, 768)

In [19]:
embeddings = embeddings.append(one_embedding)
detected_similar = list_similar_embeddings(new_sr_dict['u_case_number'], embeddings, similarity_threshold=0.25, quantity_threshold=10)
detected_similar

TypeError: list_similar_embeddings() missing 1 required positional argument: 'query_identifier'

In [ ]:
transformed_df[transformed_df['u_case_number']==90249826].values

In [ ]:
new_sr_description = 'this is a test description'
new_sr_dict = {'u_case_number': 12345,
               'u_problem_description': new_sr_description,
               'u_solution_description': '',
               'u_expert_assessment_descriptio': '', 
               'u_first_reply_solution': ''}


old_df = pd.read_csv('tests/fixtures/miniSRdf.csv')
saved_embeddings = pd.read_csv('tests/fixtures/embeddings_df.csv', index_col='u_case_number')
similar, updated_df, updated_embeddings = get_list_of_similar_SR(saved_embeddings, sr_df = old_df,
                                                                 sr_id = 12345, sr_dict = new_sr_dict,
                                                                 similarity_threshold=0.25,
                                                                 quantity_threshold=10)

In [ ]:
similar